name: Child Workflow
on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string

jobs:
  print-message:
    runs-on: ubuntu-latest
    steps:
      - name: Print the message
        run: echo "Message from caller:${{ inputs.message }}"
